# Generated by Powerlevel10k configuration wizard.
# Custom Carl KDE Theme - git venv hostname@username directory  

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # --- CARL KDE THEME COLORS ---
  local teal='116'
  local peach='209'
  local lavender='147'
  local white='255'
  local purple='105'
  local red='1'

  # 1. PROMPT ORDER (git venv hostname@username dir ->)
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    vcs                 # git
    virtualenv          # venv
    context             # hostname@username
    dir                 # directory
    prompt_char         # 
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

  # 2. SPACING CONTROL (1 space after each)
  typeset -g POWERLEVEL9K_VCS_PREFIX=''
  typeset -g POWERLEVEL9K_VCS_SUFFIX=' '
  
  typeset -g POWERLEVEL9K_VIRTUALENV_PREFIX=''
  typeset -g POWERLEVEL9K_VIRTUALENV_SUFFIX=' '

  typeset -g POWERLEVEL9K_DIR_PREFIX=''
  typeset -g POWERLEVEL9K_DIR_SUFFIX=' '

  # 3. CONTEXT (hostname@username)
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%m@%n'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION='%m@%n'
  typeset -g POWERLEVEL9K_CONTEXT_SUFFIX=' '
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$white

  # 4. ELEMENT COLORS
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=$teal
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$peach
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$lavender
  
  # 5. THE ARROW (Nerd Font Symbol)
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='' 
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=$purple
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=$red

  # 6. LAYOUT TIGHTENING (Removes automatic double spaces)
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=''
  
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=''
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
